class Item {
    id: string;
    imgsrc: string;
    constructor(id: string, img: string) {
        this.id = id;
        this.imgsrc = img;
        Item.allItems.set(id, this);
    }

    public static allItems: Map<string, Item> = new Map();

    public static bottled_food_1: Item = new Item('bottled_food_1', '/items/item_bottled_food_1.png');
    public static bottled_food_2: Item = new Item('bottled_food_2', '/items/item_bottled_food_2.png');
    public static bottled_food_3: Item = new Item('bottled_food_3', '/items/item_bottled_food_3.png');
    public static bottled_food_4: Item = new Item('bottled_food_4', '/items/item_bottled_food_4.png');
    public static bottled_rec_hp_1: Item = new Item('bottled_rec_hp_1', '/items/item_bottled_rec_hp_1.png');
    public static bottled_rec_hp_2: Item = new Item('bottled_rec_hp_2', '/items/item_bottled_rec_hp_2.png');
    public static bottled_rec_hp_3: Item = new Item('bottled_rec_hp_3', '/items/item_bottled_rec_hp_3.png');
    public static bottled_rec_hp_4: Item = new Item('bottled_rec_hp_4', '/items/item_bottled_rec_hp_4.png');
    public static carbon_enr: Item = new Item('carbon_enr', '/items/item_carbon_enr.png');
    public static carbon_enr_powder: Item = new Item('carbon_enr_powder', '/items/item_carbon_enr_powder.png');
    public static carbon_mtl: Item = new Item('carbon_mtl', '/items/item_carbon_mtl.png');
    public static carbon_powder: Item = new Item('carbon_powder', '/items/item_carbon_powder.png');
    public static crystal_enr: Item = new Item('crystal_enr', '/items/item_crystal_enr.png');
    public static crystal_enr_powder: Item = new Item('crystal_enr_powder', '/items/item_crystal_enr_powder.png');
    public static crystal_powder: Item = new Item('crystal_powder', '/items/item_crystal_powder.png');
    public static crystal_shell: Item = new Item('crystal_shell', '/items/item_crystal_shell.png');
    public static equip_script_1: Item = new Item('equip_script_1', '/items/item_equip_script_1.png');
    public static equip_script_2: Item = new Item('equip_script_2', '/items/item_equip_script_2.png');
    public static equip_script_3: Item = new Item('equip_script_3', '/items/item_equip_script_3.png');
    public static equip_script_4: Item = new Item('equip_script_4', '/items/item_equip_script_4.png');
    public static fbottle_glassenr_grass_1: Item = new Item('fbottle_glassenr_grass_1', '/items/item_fbottle_glassenr_grass_1.png');
    public static fbottle_glassenr_grass_2: Item = new Item('fbottle_glassenr_grass_2', '/items/item_fbottle_glassenr_grass_2.png');
    public static fbottle_glassenr_water: Item = new Item('fbottle_glassenr_water', '/items/item_fbottle_glassenr_water.png');
    public static fbottle_glassenr_xiranite: Item = new Item('fbottle_glassenr_xiranite', '/items/item_fbottle_glassenr_xiranite.png');
    public static fbottle_glass_grass_1: Item = new Item('fbottle_glass_grass_1', '/items/item_fbottle_glass_grass_1.png');
    public static fbottle_glass_grass_2: Item = new Item('fbottle_glass_grass_2', '/items/item_fbottle_glass_grass_2.png');
    public static fbottle_glass_water: Item = new Item('fbottle_glass_water', '/items/item_fbottle_glass_water.png');
    public static fbottle_glass_xiranite: Item = new Item('fbottle_glass_xiranite', '/items/item_fbottle_glass_xiranite.png');
    public static fbottle_ironenr_grass_1: Item = new Item('fbottle_ironenr_grass_1', '/items/item_fbottle_ironenr_grass_1.png');
    public static fbottle_ironenr_grass_2: Item = new Item('fbottle_ironenr_grass_2', '/items/item_fbottle_ironenr_grass_2.png');
    public static fbottle_ironenr_water: Item = new Item('fbottle_ironenr_water', '/items/item_fbottle_ironenr_water.png');
    public static fbottle_ironenr_xiranite: Item = new Item('fbottle_ironenr_xiranite', '/items/item_fbottle_ironenr_xiranite.png');
    public static fbottle_iron_grass_1: Item = new Item('fbottle_iron_grass_1', '/items/item_fbottle_iron_grass_1.png');
    public static fbottle_iron_grass_2: Item = new Item('fbottle_iron_grass_2', '/items/item_fbottle_iron_grass_2.png');
    public static fbottle_iron_water: Item = new Item('fbottle_iron_water', '/items/item_fbottle_iron_water.png');
    public static fbottle_iron_xiranite: Item = new Item('fbottle_iron_xiranite', '/items/item_fbottle_iron_xiranite.png');
    public static glass_bottle: Item = new Item('glass_bottle', '/items/item_glass_bottle.png');
    public static glass_cmpt: Item = new Item('glass_cmpt', '/items/item_glass_cmpt.png');
    public static glass_enr_bottle: Item = new Item('glass_enr_bottle', '/items/item_glass_enr_bottle.png');
    public static glass_enr_cmpt: Item = new Item('glass_enr_cmpt', '/items/item_glass_enr_cmpt.png');
    public static iron_bottle: Item = new Item('iron_bottle', '/items/item_iron_bottle.png');
    public static iron_cmpt: Item = new Item('iron_cmpt', '/items/item_iron_cmpt.png');
    public static iron_enr: Item = new Item('iron_enr', '/items/item_iron_enr.png');
    public static iron_enr_bottle: Item = new Item('iron_enr_bottle', '/items/item_iron_enr_bottle.png');
    public static iron_enr_cmpt: Item = new Item('iron_enr_cmpt', '/items/item_iron_enr_cmpt.png');
    public static iron_enr_powder: Item = new Item('iron_enr_powder', '/items/item_iron_enr_powder.png');
    public static iron_nugget: Item = new Item('iron_nugget', '/items/item_iron_nugget.png');
    public static iron_ore: Item = new Item('iron_ore', '/items/item_iron_ore.png');
    public static iron_powder: Item = new Item('iron_powder', '/items/item_iron_powder.png');
    public static liquid_plant_grass_1: Item = new Item('liquid_plant_grass_1', '/items/item_liquid_plant_grass_1.png');
    public static liquid_plant_grass_2: Item = new Item('liquid_plant_grass_2', '/items/item_liquid_plant_grass_2.png');
    public static liquid_water: Item = new Item('liquid_water', '/items/item_liquid_water.png');
    public static liquid_xiranite: Item = new Item('liquid_xiranite', '/items/item_liquid_xiranite.png');
    public static muck_feces_1: Item = new Item('muck_feces_1', '/items/item_muck_feces_1.png');
    public static muck_xiranite_1: Item = new Item('muck_xiranite_1', '/items/item_muck_xiranite_1.png');
    public static originium_enr_powder: Item = new Item('originium_enr_powder', '/items/item_originium_enr_powder.png');
    public static originium_ore: Item = new Item('originium_ore', '/items/item_originium_ore.png');
    public static originium_powder: Item = new Item('originium_powder', '/items/item_originium_powder.png');
    public static plant_bbflower_1: Item = new Item('plant_bbflower_1', '/items/item_plant_bbflower_1.png');
    public static plant_bbflower_powder_1: Item = new Item('plant_bbflower_powder_1', '/items/item_plant_bbflower_powder_1.png');
    public static plant_bbflower_seed_1: Item = new Item('plant_bbflower_seed_1', '/items/item_plant_bbflower_seed_1.png');
    public static plant_grass_1: Item = new Item('plant_grass_1', '/items/item_plant_grass_1.png');
    public static plant_grass_2: Item = new Item('plant_grass_2', '/items/item_plant_grass_2.png');
    public static plant_grass_powder_1: Item = new Item('plant_grass_powder_1', '/items/item_plant_grass_powder_1.png');
    public static plant_grass_powder_2: Item = new Item('plant_grass_powder_2', '/items/item_plant_grass_powder_2.png');
    public static plant_grass_seed_1: Item = new Item('plant_grass_seed_1', '/items/item_plant_grass_seed_1.png');
    public static plant_grass_seed_2: Item = new Item('plant_grass_seed_2', '/items/item_plant_grass_seed_2.png');
    public static plant_moss_1: Item = new Item('plant_moss_1', '/items/item_plant_moss_1.png');
    public static plant_moss_2: Item = new Item('plant_moss_2', '/items/item_plant_moss_2.png');
    public static plant_moss_3: Item = new Item('plant_moss_3', '/items/item_plant_moss_3.png');
    public static plant_moss_enr_powder_1: Item = new Item('plant_moss_enr_powder_1', '/items/item_plant_moss_enr_powder_1.png');
    public static plant_moss_enr_powder_2: Item = new Item('plant_moss_enr_powder_2', '/items/item_plant_moss_enr_powder_2.png');
    public static plant_moss_powder_1: Item = new Item('plant_moss_powder_1', '/items/item_plant_moss_powder_1.png');
    public static plant_moss_powder_2: Item = new Item('plant_moss_powder_2', '/items/item_plant_moss_powder_2.png');
    public static plant_moss_powder_3: Item = new Item('plant_moss_powder_3', '/items/item_plant_moss_powder_3.png');
    public static plant_moss_seed_1: Item = new Item('plant_moss_seed_1', '/items/item_plant_moss_seed_1.png');
    public static plant_moss_seed_2: Item = new Item('plant_moss_seed_2', '/items/item_plant_moss_seed_2.png');
    public static plant_moss_seed_3: Item = new Item('plant_moss_seed_3', '/items/item_plant_moss_seed_3.png');
    public static plant_sp_1: Item = new Item('plant_sp_1', '/items/item_plant_sp_1.png');
    public static plant_sp_2: Item = new Item('plant_sp_2', '/items/item_plant_sp_2.png');
    public static plant_sp_3: Item = new Item('plant_sp_3', '/items/item_plant_sp_3.png');
    public static plant_sp_4: Item = new Item('plant_sp_4', '/items/item_plant_sp_4.png');
    public static plant_sp_seed_1: Item = new Item('plant_sp_seed_1', '/items/item_plant_sp_seed_1.png');
    public static plant_sp_seed_2: Item = new Item('plant_sp_seed_2', '/items/item_plant_sp_seed_2.png');
    public static plant_sp_seed_3: Item = new Item('plant_sp_seed_3', '/items/item_plant_sp_seed_3.png');
    public static plant_sp_seed_4: Item = new Item('plant_sp_seed_4', '/items/item_plant_sp_seed_4.png');
    public static plant_tundra_wood: Item = new Item('plant_tundra_wood', '/items/item_plant_tundra_wood.png');
    public static proc_battery_1: Item = new Item('proc_battery_1', '/items/item_proc_battery_1.png');
    public static proc_battery_2: Item = new Item('proc_battery_2', '/items/item_proc_battery_2.png');
    public static proc_battery_3: Item = new Item('proc_battery_3', '/items/item_proc_battery_3.png');
    public static proc_battery_4: Item = new Item('proc_battery_4', '/items/item_proc_battery_4.png');
    public static proc_bomb_1: Item = new Item('proc_bomb_1', '/items/item_proc_bomb_1.png');
    public static quartz_enr: Item = new Item('quartz_enr', '/items/item_quartz_enr.png');
    public static quartz_enr_powder: Item = new Item('quartz_enr_powder', '/items/item_quartz_enr_powder.png');
    public static quartz_glass: Item = new Item('quartz_glass', '/items/item_quartz_glass.png');
    public static quartz_powder: Item = new Item('quartz_powder', '/items/item_quartz_powder.png');
    public static quartz_sand: Item = new Item('quartz_sand', '/items/item_quartz_sand.png');
    public static xiranite_powder: Item = new Item('xiranite_powder', '/items/item_xiranite_powder.png');
}

export default Item;
